### PR TITLE
fix: fixed deck shuffle bug #20

### LINKED ISSUE #20: Card remains fliped after shuffle
If a card is face up when the deck is shuffled, it will stay face up in the deck.

### PR DESCRIPTION
**Pull request by thomas-rocha**
When shuffle is clicked, check if top card is face up and flip it. Restart shuffle function after animation is complete.

### CODE REVIEW

**Comment by Sentixxx** [comment]
still have the bug
image

File: script/main.js [hunk 1]
```diff
@@ -35,6 +36,15 @@ document.addEventListener('DOMContentLoaded', () => {
         // Only get visible cards for animation (max 3)
         const visibleCards = Array.from(allCards).filter(card => card.style.display !== 'none');
         const cardsToAnimate = visibleCards.slice(0, 3);
+        const topCardFlipped = false;
+        cardsToAnimate.forEach(card => {
+            if(card._isFaceUp){
```
Comment (Sentixxx) [inline script/main.js:41]: Can we check the deck state? If the whole deck is fliped, then it should remain fliped(if it is currently backside but the whole deck is frontside)

**Review by Sentixxx — APPROVED** [review]

File: script/main.js (hunk 1 above)
Comment (thomas-rocha) [reply script/main.js:41]: I dont see a way or reason for the whole deck to be face up. In my head, when the shuffle button is pressed all cards should go face down and back into the deck. This might just be an interpretation difference.

Comment (Sentixxx) [reply script/main.js:41]: > I dont see a way or reason for the whole deck to be face up. In my head, when the shuffle button is pressed all cards should go face down and back into the deck. This might just be an interpretation difference.

You’re right. I misunderstood the requirement.
